version: 2

sources:
  - name: discorama
    database: desafio-lh  
    schema: raw
    description: Fonte de dados da discorama 
    tables:
      - name: actors
        columns:
        - name: actor_id
          description: primary key da tabela actors
          tests:
            - unique
            - not_null
      - name: address
        columns:
        - name: address_id
          description: primary key da tabela address
          tests:
            - unique
            - not_null
      - name: categories
        columns:
        - name: category_id
          description: primary key da tabela categories
          tests:
            - unique
            - not_null
      - name: cities
        columns:
          - name: city_id
            description: primary key da tabela cities
            tests:
              - unique
              - not_null
      - name: countries
        columns:
          - name: country_id
            description: primary key da tabela countries
            tests:
              - unique
              - not_null
      - name: customers
        columns:
          - name: customer_id
            description: primary key da tabela customers
            tests:
              - unique
              - not_null
      - name: film_categories
      - name: film_actors
      - name: films
        columns:
          - name: film_id
            description: primary key da tabela films
            tests:
              - unique
              - not_null
      - name: inventory
        columns:
          - name: inventory_id
            description: primary key da tabela inventory
            tests:
              - unique
              - not_null
      - name: payments
        columns:
          - name: payment_id
            description: primary key da tabela payments
            tests:
              - unique
              - not_null
      - name: rentals
        columns:
          - name: rental_id
            description: primary key da tabela rentals
            tests:
              - unique
              - not_null
      - name: staff
        columns:
          - name: staff_id
            description: primary key da tabela staff
            tests:
              - unique
              - not_null
      - name: stores
        columns:
          - name: store_id
            description: primary key da tabela stores
            tests:
              - unique
              - not_null
